openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /upload:
    post:
      operationId: image.upload
      summary: Uploading a list  of images
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: >-
            The images have been uploaded
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: >-
            The set of images cant be uploaded 
          content:
            application/json:
              schema:
                type: integer